"""add_scheduled_observations_and_monitored_satellites

Revision ID: 16019e90ddb7
Revises: 16d276c75884
Create Date: 2026-01-04 20:28:01.366424

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import DateTime

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16019e90ddb7"
down_revision: Union[str, None] = "16d276c75884"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitored_satellites",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("norad_id", sa.Integer(), nullable=False),
        sa.Column("sdr_id", sa.UUID(), nullable=True),
        sa.Column("rotator_id", sa.UUID(), nullable=True),
        sa.Column("rig_id", sa.UUID(), nullable=True),
        sa.Column("satellite_config", sa.JSON(), nullable=False),
        sa.Column("hardware_config", sa.JSON(), nullable=False),
        sa.Column("generation_config", sa.JSON(), nullable=False),
        sa.Column("tasks", sa.JSON(), nullable=False),
        sa.Column("created_at", DateTime(timezone=False), nullable=False),
        sa.Column("updated_at", DateTime(timezone=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["norad_id"],
            ["satellites.norad_id"],
        ),
        sa.ForeignKeyConstraint(
            ["rig_id"],
            ["rigs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rotator_id"],
            ["rotators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sdr_id"],
            ["sdrs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("monitored_satellites", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_monitored_satellites_enabled"), ["enabled"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_monitored_satellites_norad_id"), ["norad_id"], unique=True
        )

    op.create_table(
        "scheduled_observations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED", "RUNNING", "COMPLETED", "CANCELLED", "FAILED", name="observationstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("norad_id", sa.Integer(), nullable=False),
        sa.Column("event_start", DateTime(timezone=False), nullable=False),
        sa.Column("event_end", DateTime(timezone=False), nullable=False),
        sa.Column("sdr_id", sa.UUID(), nullable=True),
        sa.Column("rotator_id", sa.UUID(), nullable=True),
        sa.Column("rig_id", sa.UUID(), nullable=True),
        sa.Column("satellite_config", sa.JSON(), nullable=False),
        sa.Column("pass_config", sa.JSON(), nullable=False),
        sa.Column("hardware_config", sa.JSON(), nullable=False),
        sa.Column("tasks", sa.JSON(), nullable=False),
        sa.Column("created_at", DateTime(timezone=False), nullable=False),
        sa.Column("updated_at", DateTime(timezone=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["norad_id"],
            ["satellites.norad_id"],
        ),
        sa.ForeignKeyConstraint(
            ["rig_id"],
            ["rigs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rotator_id"],
            ["rotators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sdr_id"],
            ["sdrs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scheduled_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scheduled_observations_enabled"), ["enabled"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_observations_event_start"), ["event_start"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_observations_norad_id"), ["norad_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_observations_status"), ["status"], unique=False
        )

    op.create_table(
        "generated_observations",
        sa.Column("observation_id", sa.String(), nullable=False),
        sa.Column("monitored_satellite_id", sa.String(), nullable=False),
        sa.Column("generated_at", DateTime(timezone=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitored_satellite_id"], ["monitored_satellites.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"], ["scheduled_observations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("observation_id"),
    )
    with op.batch_alter_table("generated_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_generated_observations_monitored_satellite_id"),
            ["monitored_satellite_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generated_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generated_observations_monitored_satellite_id"))

    op.drop_table("generated_observations")
    with op.batch_alter_table("scheduled_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduled_observations_status"))
        batch_op.drop_index(batch_op.f("ix_scheduled_observations_norad_id"))
        batch_op.drop_index(batch_op.f("ix_scheduled_observations_event_start"))
        batch_op.drop_index(batch_op.f("ix_scheduled_observations_enabled"))

    op.drop_table("scheduled_observations")
    with op.batch_alter_table("monitored_satellites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monitored_satellites_norad_id"))
        batch_op.drop_index(batch_op.f("ix_monitored_satellites_enabled"))

    op.drop_table("monitored_satellites")
    # ### end Alembic commands ###
