"""Initial schema

Revision ID: 5eef1a43935a
Revises:
Create Date: 2025-10-10 18:53:15.620859

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import JSON, DateTime

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5eef1a43935a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cameras",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("type", sa.Enum("WEBRTC", "HLS", "MJPEG", name="cameratype", native_enum=False), nullable=False),
        sa.Column("status", sa.Enum("active", "inactive", native_enum=False), nullable=False),
        sa.Column("added", DateTime(timezone=False), nullable=False),
        sa.Column("updated", DateTime(timezone=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rigs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("radiotype", sa.String(), nullable=False),
        sa.Column("pttstatus", sa.Integer(), nullable=False),
        sa.Column("vfotype", sa.Integer(), nullable=False),
        sa.Column("lodown", sa.Integer(), nullable=False),
        sa.Column("loup", sa.Integer(), nullable=False),
        sa.Column("added", DateTime(timezone=False), nullable=False),
        sa.Column("updated", DateTime(timezone=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rotators",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("minaz", sa.Integer(), nullable=False),
        sa.Column("maxaz", sa.Integer(), nullable=False),
        sa.Column("minel", sa.Integer(), nullable=False),
        sa.Column("maxel", sa.Integer(), nullable=False),
        sa.Column("aztype", sa.Integer(), nullable=False),
        sa.Column("azendstop", sa.Integer(), nullable=False),
        sa.Column("added", DateTime(timezone=False), nullable=False),
        sa.Column("updated", DateTime(timezone=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "satellites",
        sa.Column("norad_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_other", sa.String(), nullable=True),
        sa.Column("alternative_name", sa.String(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("sat_id", sa.String(), nullable=True),
        sa.Column("tle1", sa.String(), nullable=False),
        sa.Column("tle2", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("decayed", DateTime(timezone=False), nullable=True),
        sa.Column("launched", DateTime(timezone=False), nullable=True),
        sa.Column("deployed", DateTime(timezone=False), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("operator", sa.String(), nullable=True),
        sa.Column("countries", sa.String(), nullable=True),
        sa.Column("citation", sa.String(), nullable=True),
        sa.Column("is_frequency_violator", sa.Boolean(), nullable=True),
        sa.Column("associated_satellites", sa.String(), nullable=True),
        sa.Column("added", DateTime(timezone=False), nullable=False),
        sa.Column("updated", DateTime(timezone=False), nullable=True),
        sa.PrimaryKeyConstraint("norad_id"),
        sa.UniqueConstraint("norad_id"),
    )
    op.create_table(
        "sdrs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("serial", sa.String(), nullable=True),
        sa.Column("host", sa.String(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "RTLSDRUSBV3",
                "RTLSDRTCPV3",
                "RTLSDRUSBV4",
                "RTLSDRTCPV4",
                "SOAPYSDRLOCAL",
                "SOAPYSDRREMOTE",
                "UHD",
                name="sdrtype",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("driver", sa.String(), nullable=True),
        sa.Column("frequency_min", sa.Integer(), nullable=True),
        sa.Column("frequency_max", sa.Integer(), nullable=True),
        sa.Column("added", DateTime(timezone=False), nullable=False),
        sa.Column("updated", DateTime(timezone=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tle_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("added", DateTime(timezone=False), nullable=False),
        sa.Column("updated", DateTime(timezone=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tracking_state",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("added", DateTime(timezone=False), nullable=False),
        sa.Column("updated", DateTime(timezone=False), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tracking_state", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tracking_state_name"), ["name"], unique=True)

    op.create_table(
        "groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("identifier", sa.String(), nullable=True),
        sa.Column("type", sa.Enum("USER", "SYSTEM", name="satellitegrouptype", native_enum=False), nullable=False),
        sa.Column("satellite_ids", JSON(), nullable=True),
        sa.Column("added", DateTime(timezone=False), nullable=False),
        sa.Column("updated", DateTime(timezone=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("alt", sa.Integer(), nullable=False),
        sa.Column("added", DateTime(timezone=False), nullable=False),
        sa.Column("updated", DateTime(timezone=False), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("added", DateTime(timezone=False), nullable=False),
        sa.Column("updated", DateTime(timezone=False), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transmitters",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("alive", sa.Boolean(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("uplink_low", sa.Integer(), nullable=True),
        sa.Column("uplink_high", sa.Integer(), nullable=True),
        sa.Column("uplink_drift", sa.Integer(), nullable=True),
        sa.Column("downlink_low", sa.Integer(), nullable=True),
        sa.Column("downlink_high", sa.Integer(), nullable=True),
        sa.Column("downlink_drift", sa.Integer(), nullable=True),
        sa.Column("mode", sa.String(), nullable=True),
        sa.Column("mode_id", sa.Integer(), nullable=True),
        sa.Column("uplink_mode", sa.String(), nullable=True),
        sa.Column("invert", sa.Boolean(), nullable=True),
        sa.Column("baud", sa.Integer(), nullable=True),
        sa.Column("sat_id", sa.String(), nullable=True),
        sa.Column("norad_cat_id", sa.Integer(), nullable=False),
        sa.Column("norad_follow_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("citation", sa.String(), nullable=True),
        sa.Column("service", sa.String(), nullable=True),
        sa.Column("iaru_coordination", sa.String(), nullable=True),
        sa.Column("iaru_coordination_url", sa.String(), nullable=True),
        sa.Column("itu_notification", sa.JSON(), nullable=True),
        sa.Column("frequency_violation", sa.Boolean(), nullable=True),
        sa.Column("unconfirmed", sa.Boolean(), nullable=True),
        sa.Column("added", DateTime(timezone=False), nullable=True),
        sa.Column("updated", DateTime(timezone=False), nullable=True),
        sa.ForeignKeyConstraint(
            ["norad_cat_id"],
            ["satellites.norad_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transmitters")
    op.drop_table("preferences")
    op.drop_table("locations")
    op.drop_table("groups")
    with op.batch_alter_table("tracking_state", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracking_state_name"))

    op.drop_table("tracking_state")
    op.drop_table("tle_sources")
    op.drop_table("sdrs")
    op.drop_table("satellites")
    op.drop_table("rotators")
    op.drop_table("rigs")
    op.drop_table("cameras")
    # ### end Alembic commands ###
